name: Run Collection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        npm i
    
    - name: Run Collection
      run: |
        npm run test:api

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman
    